### ISSUE TITLE
Intrusive Admin Notices

### ISSUE THREAD

**Issue by CallumMitchellRV** [valu-digital/wp-graphql-lock#5]
The undismissable admin notices are intrusive in the CMS. Have clients who have access to the CMS and we don't want these messages to appear. We manage security to the endpoints elsewhere and want to remove the "The API is open. Anyone can send any query to it!" and "Query recording is enabled" notices without having to edit the plugin code. Can this be considered for future releases?

![image](https://user-images.githubusercontent.com/18437652/157866933-efb2bb7a-83aa-4fe3-825b-a3e13aa6c770.png)

**Comment by vvasiloud** [comment]
Hello,
The plugin seems unmaintained unfortunately.  
A simple fix would be to show the warning messages only if the current account is administrator (assuming your clients don't login with elevated rights account on daily basis).

Adding `if(is_admin()) ` on: https://github.com/valu-digital/wp-graphql-lock/blob/0354a937c669fd2c42fbce5c6c05d5a0ebf06f07/src/settings.php#L107 could do the trick.

**Comment by CallumMitchellRV** [comment]
Thanks, I've resorted to something similar. I appreciate the help
